# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0006_auto_20161205_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='ip_address',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
