# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0010_room_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='ref_id',
        ),
    ]
