# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0011_remove_room_ref_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smart_devices',
            old_name='deadline',
            new_name='deadlines',
        ),
        migrations.RemoveField(
            model_name='smart_devices',
            name='description',
        ),
    ]
