# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0011_remove_room_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optimal_Status_Fridges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(default=0, max_length=100)),
                ('status', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Optimal_Status_Heating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(default=0, max_length=100)),
                ('status', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Optimal_Status_Smart_Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(default=0, max_length=100)),
                ('status', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Status_Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(default=0, max_length=100)),
                ('status', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Status_Fridges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(default=0, max_length=100)),
                ('status', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Status_Heating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(default=0, max_length=100)),
                ('status', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Status_Stupid_devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(default=0, max_length=100)),
                ('status', models.CharField(default=0, max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Stupid_Devices')),
            ],
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='ip_address',
            new_name='ref_id',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='ip_address',
            new_name='ref_id',
        ),
        migrations.AddField(
            model_name='battery',
            name='charged_status',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='battery',
            name='optimal_status',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='fridges',
            name='optimal_status',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='fridges',
            name='planned_status',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='heating',
            name='optimal_status',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='heating',
            name='planned_status',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='smart_devices',
            name='optimal_status',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='smart_devices',
            name='status_function',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='plan_status_heating',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Heating'),
        ),
        migrations.AddField(
            model_name='plan_status_fridges',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Fridges'),
        ),
        migrations.AddField(
            model_name='plan_status_battery',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Battery'),
        ),
        migrations.AddField(
            model_name='optimal_status_smart_devices',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Fridges'),
        ),
        migrations.AddField(
            model_name='optimal_status_heating',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Fridges'),
        ),
        migrations.AddField(
            model_name='optimal_status_fridges',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Fridges'),
        ),
    ]
