# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0012_auto_20161212_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='deadlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='smart_devices',
            name='deadlines',
        ),
        migrations.AddField(
            model_name='deadlines',
            name='smart_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Smart_Devices'),
        ),
    ]
