# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0012_auto_20161213_2319'),
        ('neighbourhood', '0013_auto_20161214_1115'),
    ]

    operations = [
    ]
