# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0014_merge_20161215_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heating',
            old_name='house',
            new_name='House',
        ),
        migrations.AddField(
            model_name='smart_devices',
            name='deadlin',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='smart_devices',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stupid_devices',
            name='deadlin',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='stupid_devices',
            name='duration',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
