# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0015_auto_20161219_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heating',
            old_name='House',
            new_name='house',
        ),
        migrations.RemoveField(
            model_name='stupid_devices',
            name='duration',
        ),
    ]
