# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0016_auto_20161219_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='stupid_devices',
            name='duration',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
